name: Automated infra provisioning with Terraform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

env:
  AWS_REGION : "us-east-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_GH_ACTION_ROLE_ARN }}
  AWS_BACKEND_BUCKET: ${{ secrets.AWS_BACKEND_BUCKET }}
  DB_NAME: ${{ secrets.DB_NAME }}
  ENV: "prod"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  TerraformProvisioning:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-01
    steps:        
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
      
      - name: Terraform switch workspace
        id: switch
        run: terraform workspace select ${{ env.ENV }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: |
          cat > ci.auto.tfvars <<EOF
          env = "${{ env.ENV }}"
          state_file_bucket = "${{ env.AWS_BACKEND_BUCKET }}"
          region = "${{ env.AWS_REGION }}"
          db_name = "${{ env.DB_NAME }}"
          EOF
          terraform apply -auto-approve -input=false

  AnsibleConfiguration: 
    runs-on: ubuntu-latest
    needs: TerraformProvisioning
    defaults:
      run:
        working-directory: ./ansible-01
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
      
      - name: Terraform switch workspace
        id: switch
        run: terraform workspace select ${{ env.ENV }}
      
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.1'
        continue-on-error: true
        
      - name: Build release C#
        run: dotnet publish -c release -o ../ansible-01/cout
        working-directory: ./try-02
      
      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Update envs and secrets to latest
        run: bun script

      - name: Install Ansible
        run: sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ./inventory.ini ./deploy.yml
      
