name: Automated infra provisioning and deployment

on:
  workflow_run:
    workflows: ["CI and build"]
    types: [completed]
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_GH_ACTION_ROLE_ARN }}
  AWS_BACKEND_BUCKET: ${{ secrets.AWS_BACKEND_BUCKET }}
  AWS_SSH_KEY_NAME: ${{ secrets.AWS_SSH_KEY_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  APP_NAME: "dotnetapi"
  ENV: "prod"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  InfraProvisioning:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-01
    steps:        
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.1

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
      
      - name: Terraform switch workspace
        id: switch
        run: terraform workspace select ${{ env.ENV }}

      - name: Terraform Apply
        id: apply
        run: |
          cat > ci.auto.tfvars <<EOF
          env = "${{ env.ENV }}"
          state_file_bucket = "${{ env.AWS_BACKEND_BUCKET }}"
          region = "${{ env.AWS_REGION }}"
          db_name = "${{ env.DB_NAME }}"
          ec2_key_name = "${{ env.AWS_SSH_KEY_NAME }}"
          EOF
          terraform apply -auto-approve

  AnsibleConfiguration: 
    runs-on: ubuntu-latest
    environment: delayed_deployment
    needs: InfraProvisioning
    defaults:
      run:
        working-directory: ./ansible-01
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
        working-directory: ./terraform-01
      
      - name: Terraform switch workspace
        id: switch
        run: terraform workspace select ${{ env.ENV }}
        working-directory: ./terraform-01
      
      - name: Fetch Bucket Name
        id: fetch_bucket
        run: |
          NAME=$(aws s3api list-buckets --prefix "${{ env.APP_NAME }}-${{ env.ENV }}-build-files" --query "Buckets[0].Name" --output text)
          echo "bucket_name=$NAME" >> "$GITHUB_OUTPUT"  

      - name: Fetch Ansible password
        id: fetch_ansible_password
        run: |
          NAME=$(aws secretsmanager list-secrets --filters Key="name",Values="${{ env.APP_NAME }}-${{ env.ENV}}-ansible-password" --query 'SecretList[0].Name' --output text)
          PASSWORD=$(aws secretsmanager get-secret-value --secret-id $NAME --query "SecretString" --output text)
          echo "password=$PASSWORD" >> "$GITHUB_OUTPUT" 
          
      - name: Build Connection string
        id: build_db_conn_string
        run: |
          NAME=$(aws secretsmanager list-secrets --filters Key="name",Values="${{ env.APP_NAME }}-${{ env.ENV}}-db-" --query 'SecretList[0].Name' --output text)
          JSON_OUT=$(aws secretsmanager get-secret-value --secret-id $NAME --query "SecretString" --output text)
          PORT=$(echo $JSON_OUT | jq -r '.port')
          HOST=$(echo $JSON_OUT | jq -r '.host')
          DB_NAME=$(echo $JSON_OUT | jq -r '.db_name')
          USERNAME=$(echo $JSON_OUT | jq -r '.username')
          PASSWORD=$(echo $JSON_OUT | jq -r '.password')
          CONNECTION_STRING="Host=$HOST;Port=$PORT;Database=$DB_NAME;Username=$USERNAME;Password=$PASSWORD"
          echo "connection_string=$CONNECTION_STRING" >> "$GITHUB_OUTPUT"

      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Update envs and secrets to latest
        run: bun script

      - name: Install Ansible and Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible pywinrm requests

      - name: Install Windows collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible Playbook
        env:
          BUILD_FILES_BUCKET: ${{ steps.fetch_bucket.outputs.bucket_name }}
          COMMIT_SHA: ${{ github.event.workflow_run.head_sha || github.sha }}
          ANSIBLE_PASSWORD: ${{ steps.fetch_ansible_password.outputs.password }}
          DB_CONNECTION_STRING: ${{ steps.build_db_conn_string.outputs.connection_string }} 
        run: |
          ansible-playbook -i ./inventory.ini ./deploy.yml
      
