name: Automated infra provisioning and deployment

on:
  # push:
  #   branches: [ main ]
  workflow_run:
    workflows: ["CI and build"]
    types: [completed]
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_GH_ACTION_ROLE_ARN }}
  AWS_BACKEND_BUCKET: ${{ secrets.AWS_BACKEND_BUCKET }}
  AWS_SSH_KEY_NAME: ${{ secrets.AWS_SSH_KEY_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  APP_NAME: "dotnetapi"
  ENV: "prod"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  TerraformProvisioning:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-01
    steps:        
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.1

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
      
      - name: Terraform switch workspace
        id: switch
        run: terraform workspace select ${{ env.ENV }}

      - name: Terraform Apply
        id: apply
        run: |
          cat > ci.auto.tfvars <<EOF
          env = "${{ env.ENV }}"
          state_file_bucket = "${{ env.AWS_BACKEND_BUCKET }}"
          region = "${{ env.AWS_REGION }}"
          db_name = "${{ env.DB_NAME }}"
          ec2_key_name = "${{ env.AWS_SSH_KEY_NAME }}"
          EOF
          terraform apply -auto-approve

  AnsibleConfiguration: 
    runs-on: ubuntu-latest
    needs: TerraformProvisioning
    defaults:
      run:
        working-directory: ./ansible-01
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
        working-directory: ./terraform-01
      
      - name: Terraform switch workspace
        id: switch
        run: terraform workspace select ${{ env.ENV }}
        working-directory: ./terraform-01
      
      - name: Fetch Bucket Name
        id: fetch_bucket
        run: |
          NAME=$(aws s3api list-buckets --prefix "${{ env.APP_NAME }}-${{ env.ENV }}-build-files" --query "Buckets[0].Name" --output text)
          echo "bucket_name=$NAME" >> "$GITHUB_OUTPUT"  
    
      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Update envs and secrets to latest
        run: bun script

      - name: Install Ansible and Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible pywinrm requests

      - name: Install Windows collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible Playbook
        env:
          BUILD_FILES_BUCKET: ${{ steps.fetch_bucket.outputs.bucket_name }}
          COMMIT_SHA: ${{ github.event.workflow_run.head_sha || github.sha }}
        run: |
          ansible-playbook -i ./inventory.ini ./deploy.yml
      
