name: CI and build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_GH_ACTION_ROLE_ARN }}
  AWS_BACKEND_BUCKET: ${{ secrets.AWS_BACKEND_BUCKET }}
  AWS_SSH_KEY_NAME: ${{ secrets.AWS_SSH_KEY_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  APP_NAME: "dotnetapi"
  ENV: "prod"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  TerraformChecks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-01
    steps:        
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.1

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
      
      - name: Terraform switch workspace
        id: switch
        run: terraform workspace select ${{ env.ENV }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform formatting check
        id: format
        run: terraform fmt -check

      - name: Fetch Bucket Name
        id: fetch_bucket
        run: |
          NAME=$(aws s3api list-buckets --prefix "${{ env.APP_NAME }}-${{ env.ENV }}-build-files" --query "Buckets[0].Name" --output text)
          echo "bucket_id=$NAME" >> "$GITHUB_OUTPUT"

      - name: Terraform Plan
        id: plan
        run: |
          cat > ci.auto.tfvars <<EOF
          env = "${{ env.ENV }}"
          state_file_bucket = "${{ env.AWS_BACKEND_BUCKET }}"
          region = "${{ env.AWS_REGION }}"
          db_name = "${{ env.DB_NAME }}"
          ec2_key_name = "${{ env.AWS_SSH_KEY_NAME }}"
          EOF
          terraform plan -out planfile

      - name: Save build to s3
        run: aws s3 cp ./planfile "s3://${{ steps.fetch_bucket.outputs.bucket_id  }}/${{ github.sha }}/terraform"

  DotNetBuild: 
    runs-on: ubuntu-latest
    needs: TerraformChecks
    defaults:
      run:
        working-directory: ./try-02
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
        continue-on-error: true
        
      - name: Build release C#
        run: dotnet publish -c release -o ./cout

      - name: Fetch Bucket Name
        id: fetch_bucket
        run: |
          NAME=$(aws s3api list-buckets --prefix "${{ env.APP_NAME }}-${{ env.ENV }}-build-files" --query "Buckets[0].Name" --output text)
          echo "bucket_id=$NAME" >> "$GITHUB_OUTPUT"
      
      - name: Save build to s3
        run: aws s3 cp ./cout "s3://${{ steps.fetch_bucket.outputs.bucket_id  }}/${{ github.sha }}/build" --recursive
      
